!!python/object/new:dynamic_reconfigure.encoding.Config
dictitems:
  AdaptiveThrs: true
  AdaptiveThrsMult: 5.0
  AutoInit: false
  AutoInitPixel: 20
  BundleDebugMessages: false
  BundleMethod: LOCAL_GLOBAL
  CheckInitMapVar: false
  CoarseMax: 60.0
  CoarseMin: 20.0
  CoarseMinVelocity: 0.006
  CoarseRange: 30.0
  CoarseSubPixIts: 8.0
  DisableCoarse: false
  EpiDepthSearchMaxRange: 100.0
  FASTMethod: OAST16
  MaxIterations: 50.0
  MaxKF: 500
  MaxKFDistWiggleMult: 1.0
  MaxPatchesPerFrame: 1000.0
  MaxStereoInitLoops: 4
  MiniPatchMaxSSD: 100000
  MotionModelSource: CONSTANT
  NoLevelZeroMapPoints: true
  PlaneAlignerRansacs: 100
  RelocMaxScore: 9000000
  RotationEstimatorBlur: 0.75
  Scale: 1.0
  Thres_lvl0: 10
  Thres_lvl1: 15
  Thres_lvl2: 15
  Thres_lvl3: 10
  TrackingQualityFoundPixels: 50
  TrackingQualityGood: 0.3
  TrackingQualityLost: 0.13
  UpdateSquaredConvergenceLimit: 1.0e-06
  UseKFPixelDist: true
  UseRotationEstimator: true
  groups: !!python/object/new:dynamic_reconfigure.encoding.Config
    dictitems:
      AdaptiveThrs: true
      AdaptiveThrsMult: 5.0
      AutoInit: false
      AutoInitPixel: 20
      BundleDebugMessages: false
      BundleMethod: LOCAL_GLOBAL
      CheckInitMapVar: false
      CoarseMax: 60.0
      CoarseMin: 20.0
      CoarseMinVelocity: 0.006
      CoarseRange: 30.0
      CoarseSubPixIts: 8.0
      DisableCoarse: false
      EpiDepthSearchMaxRange: 100.0
      FASTMethod: OAST16
      MaxIterations: 50.0
      MaxKF: 500
      MaxKFDistWiggleMult: 1.0
      MaxPatchesPerFrame: 1000.0
      MaxStereoInitLoops: 4
      MiniPatchMaxSSD: 100000
      MotionModelSource: CONSTANT
      NoLevelZeroMapPoints: true
      PlaneAlignerRansacs: 100
      RelocMaxScore: 9000000
      RotationEstimatorBlur: 0.75
      Scale: 1.0
      Thres_lvl0: 10
      Thres_lvl1: 15
      Thres_lvl2: 15
      Thres_lvl3: 10
      TrackingQualityFoundPixels: 50
      TrackingQualityGood: 0.3
      TrackingQualityLost: 0.13
      UpdateSquaredConvergenceLimit: 1.0e-06
      UseKFPixelDist: true
      UseRotationEstimator: true
      groups: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      id: 0
      name: Default
      parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      parent: 0
      state: true
      type: ''
    state: []
state: []
